## Loading libs & data

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import wikipediaapi as wk
from myWiki import WikiDecadeETL

In [2]:
data = pd.read_csv("data/1900_2020s.csv")
print(data.shape)
data.head()

(528, 4)

,section,text,sub_section,decade
0,Politics and wars,Major political changes\nNew Imperialism\nThe ...,Major political changes,1900s (decade)
1,Politics and wars,Wars\nSecond Boer War ends.\nPhilippine–Americ...,Wars,1900s (decade)
2,Politics and wars,Internal conflicts\nThe Boxer Rebellion ends.\...,Internal conflicts,1900s (decade)
3,Politics and wars,"Colonization\nJanuary 1, 1901, British colonie...",Colonization,1900s (decade)
4,Politics and wars,"Decolonization\nMay 20, 1902 – Cuba gains inde...",Decolonization,1900s (decade)

In [3]:
data.tail()

,section,text,sub_section,decade
523,Culture,"Music\nIn 2020, TikTok became an important mus...",Music,2020s
524,Culture,Video games\nThe ninth generation of consoles ...,Video games,2020s
525,Culture,Architecture\n,Architecture,2020s
526,Culture,Sports\nTokyo was to host the Olympic Games fo...,Sports,2020s
527,See also,See also\nTimeline of the near future\n\n,See also,2020s

In [5]:
data.section.value_counts()

Politics and wars                          112
Popular culture                            111
People                                      69
Science and technology                      47
Disasters                                   46
Politics and conflicts                      36
Economics                                   18
Culture                                     16
Society                                     15
Assassinations and attempts                 13
See also                                     8
Social and political movements               8
Technology and science                       6
Technology                                   5
Popular memory                               2
Population and social issues                 1
Religion and irreligion                      1
Health                                       1
Economy                                      1
Cyber security and hacking                   1
Social history                               1
Health and society                           1
Cybersecurity and hacking                    1
Religion                                     1
Other significant international events       1
Worldwide trends                             1
Additional notable worldwide events          1
Name for the decade                          1
Environment and climate change               1
Environment                                  1
Additional significant worldwide events      1
Name: section, dtype: int64

In [8]:
data.sub_section.value_counts()

Assassinations and attempts        13
Prominent political events         13
Fashion                            12
Film                               12
Music                              12
                                   ..
Other natural events                1
Youth suffrage                      1
Activists and religious leaders     1
Energy crisis                       1
LGBT rights                         1
Name: sub_section, Length: 232, dtype: int64

In [6]:
data[data["section"] == "See also"]

,section,text,sub_section,decade
152,See also,Timeline\nThe following articles contain brief...,Timeline,1940s
182,See also,Timeline\nThe following articles contain brief...,Timeline,1950s
239,See also,Timelines\nThe following articles contain brie...,Timelines,1960s
288,See also,Timeline\nThe following articles contain brief...,Timeline,1970s
319,See also,Timeline\nThe following articles contain brief...,Timeline,1980s
360,See also,Timeline\nThe following articles contain brief...,Timeline,1990s
429,See also,Timeline\nThe following articles contain brief...,Timeline,2000s (decade)
527,See also,See also\nTimeline of the near future\n\n,See also,2020s

It would seem __"See also"__ wasn't completetly eliminated when transforming the pages. 

We can deal with this in 3 ways

1. Investigate this is happening and fix the bug in WikiDecadeETL
    * Bug Fixed: It was because of not excluding __Notes__ & __'Name for the decade'__ sections
2. Drop rows with "See also" when df is created in the class
3. Drop rows with "See also" when performing EDA.

We'll put this as todo for now

In [3]:
v1 = pd.read_csv("data/v2_1900_2020s.csv")

In [4]:
print(v1.shape)
v1.head()

(517, 4)

,section,text,sub_section,decade
0,Politics and wars,Major political changes\nNew Imperialism\nThe ...,Major political changes,1900s (decade)
1,Politics and wars,Wars\nSecond Boer War ends.\nPhilippine–Americ...,Wars,1900s (decade)
2,Politics and wars,Internal conflicts\nThe Boxer Rebellion ends.\...,Internal conflicts,1900s (decade)
3,Politics and wars,"Colonization\nJanuary 1, 1901, British colonie...",Colonization,1900s (decade)
4,Politics and wars,"Decolonization\nMay 20, 1902 – Cuba gains inde...",Decolonization,1900s (decade)

In [7]:
v1.tail()

,section,text,sub_section,decade
512,Culture,Television\nThe 2020s started off with the pri...,Television,2020s
513,Culture,"Music\nIn 2020, TikTok became an important mus...",Music,2020s
514,Culture,Video games\nThe ninth generation of consoles ...,Video games,2020s
515,Culture,Architecture\n,Architecture,2020s
516,Culture,Sports\nTokyo was to host the Olympic Games fo...,Sports,2020s

In [6]:
v1.section.value_counts()

Politics and wars                          112
Popular culture                            111
People                                      69
Science and technology                      47
Disasters                                   46
Politics and conflicts                      36
Economics                                   18
Culture                                     16
Society                                     15
Assassinations and attempts                 13
Social and political movements               8
Technology and science                       6
Technology                                   5
Worldwide trends                             1
Additional significant worldwide events      1
Social history                               1
Population and social issues                 1
Additional notable worldwide events          1
Cyber security and hacking                   1
Other significant international events       1
Health and society                           1
Environment                                  1
Economy                                      1
Health                                       1
Environment and climate change               1
Religion                                     1
Cybersecurity and hacking                    1
Religion and irreligion                      1
Name: section, dtype: int64

In [13]:
v1

,section,text,sub_section,decade
0,Politics and wars,Major political changes\nNew Imperialism\nThe ...,Major political changes,1900s (decade)
1,Politics and wars,Wars\nSecond Boer War ends.\nPhilippine–Americ...,Wars,1900s (decade)
2,Politics and wars,Internal conflicts\nThe Boxer Rebellion ends.\...,Internal conflicts,1900s (decade)
3,Politics and wars,"Colonization\nJanuary 1, 1901, British colonie...",Colonization,1900s (decade)
4,Politics and wars,"Decolonization\nMay 20, 1902 – Cuba gains inde...",Decolonization,1900s (decade)
...,...,...,...,...
513,Culture,Television\nThe 2020s started off with the pri...,Television,2020s
514,Culture,"Music\nIn 2020, TikTok became an important mus...",Music,2020s
515,Culture,Video games\nThe ninth generation of consoles ...,Video games,2020s
516,Culture,Architecture\n,Architecture,2020s
517,Culture,Sports\nTokyo was to host the Olympic Games fo...,Sports,2020s

In [9]:
from myWiki import WikiDecadeETL
from main import run
        

_1940s = run("1940s").core_df

In [3]:
_1940s

,section,text,sub_section,decade
0,Politics and wars,Wars\nWorld War II (1939–1945)\nNazi Germany i...,Wars,1940s
1,Politics and wars,Major political changes\nEstablishment of the ...,Major political changes,1940s
2,Politics and wars,Internal conflicts\n1947–1948 Civil War in Man...,Internal conflicts,1940s
3,Politics and wars,Decolonization and independence\n1944 – Icelan...,Decolonization and independence,1940s
4,Politics and wars,Prominent political events\n,Prominent political events,1940s
5,Economics,Economics\nThe Bretton Woods Conference was th...,Economics,1940s
6,Assassinations and attempts,Assassinations and attempts\nProminent assassi...,Assassinations and attempts,1940s
7,Science and technology,Technology\nThe Atanasoff-Berry computer is no...,Technology,1940s
8,Science and technology,Science\nPhysics: the development of quantum t...,Science,1940s
9,Popular culture,"Film\nOscar winners: Rebecca (1940), How Green...",Film,1940s
10,Popular culture,Music\nBing Crosby was the best selling pop ar...,Music,1940s
11,Popular culture,Literature\nFor Whom the Bell Tolls by Ernest ...,Literature,1940s
12,Popular culture,Fashion\nAs the 1940s went through times of ha...,Fashion,1940s
13,People,World leaders\n1940 – 1941 – 1942 – 1943 – 194...,World leaders,1940s
14,People,Military leaders\nField Marshal Erwin Rommel\n...,Military leaders,1940s
15,People,Activists and religious leaders\nJoel Brand\nB...,Activists and religious leaders,1940s
16,People,"Politics\nAbdel Rahman Azzam Pasha, Secretary-...",Politics,1940s
17,People,Actors / Entertainers\n,Actors / Entertainers,1940s
18,People,Musicians\n,Musicians,1940s
19,People,Bands\nThe Andrew Sisters\nThe Boswell Sisters...,Bands,1940s
20,People,"Sports\nDuring the 1940s, sporting events were...",Sports,1940s
21,People,Baseball\nDuring the early 1940s World War II ...,Baseball,1940s
22,People,Boxing\nDuring the mid-1930s and throughout th...,Boxing,1940s
23,People,Track and Field\n,Track and Field,1940s

 - Correlation Popular Culture & Politics and Wars
 - Economic Changes through the decades
 - Where in a century do the most significant events happen?
 
__Note__: 1800s decade onwards Wikis have a similar structure as opposed to the time periods before